/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sites */
        get: operations["list_sites_api_v1_sites_get"];
        put?: never;
        /** Create Site */
        post: operations["create_site_api_v1_sites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site */
        get: operations["get_site_api_v1_sites__site_id__get"];
        put?: never;
        post?: never;
        /** Delete Site */
        delete: operations["delete_site_api_v1_sites__site_id__delete"];
        options?: never;
        head?: never;
        /** Update Site */
        patch: operations["update_site_api_v1_sites__site_id__patch"];
        trace?: never;
    };
    "/api/v1/sites/{site_id}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Site Positions */
        get: operations["site_positions_api_v1_sites__site_id__positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enodebs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Enodebs */
        get: operations["list_enodebs_api_v1_enodebs_get"];
        put?: never;
        /** Create Enodeb */
        post: operations["create_enodeb_api_v1_enodebs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enodebs/{enodeb_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Enodeb */
        get: operations["get_enodeb_api_v1_enodebs__enodeb_id__get"];
        put?: never;
        post?: never;
        /** Delete Enodeb */
        delete: operations["delete_enodeb_api_v1_enodebs__enodeb_id__delete"];
        options?: never;
        head?: never;
        /** Update Enodeb */
        patch: operations["update_enodeb_api_v1_enodebs__enodeb_id__patch"];
        trace?: never;
    };
    "/api/v1/cells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cells */
        get: operations["list_cells_api_v1_cells_get"];
        put?: never;
        /** Create Cell */
        post: operations["create_cell_api_v1_cells_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cells/{cell_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cell */
        get: operations["get_cell_api_v1_cells__cell_id__get"];
        put?: never;
        post?: never;
        /** Delete Cell */
        delete: operations["delete_cell_api_v1_cells__cell_id__delete"];
        options?: never;
        head?: never;
        /** Update Cell */
        patch: operations["update_cell_api_v1_cells__cell_id__patch"];
        trace?: never;
    };
    "/api/v1/cells/{cell_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cell Versions */
        get: operations["cell_versions_api_v1_cells__cell_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_v1_assets_get"];
        put?: never;
        /** Create Asset */
        post: operations["create_asset_api_v1_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Asset */
        delete: operations["delete_asset_api_v1_assets__asset_id__delete"];
        options?: never;
        head?: never;
        /** Update Asset */
        patch: operations["update_asset_api_v1_assets__asset_id__patch"];
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        /** Create Device */
        post: operations["create_device_api_v1_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Device */
        delete: operations["delete_device_api_v1_devices__device_id__delete"];
        options?: never;
        head?: never;
        /** Update Device */
        patch: operations["update_device_api_v1_devices__device_id__patch"];
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/template.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template */
        get: operations["template_api_v1_inventory_template_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/export.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_v1_inventory_export_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import File
         * @description Check (dry_run=true) or apply an inventory workbook. Nothing is applied if any row fails.
         */
        post: operations["import_file_api_v1_inventory_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Map Inventory */
        get: operations["map_inventory_api_v1_map_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/basemaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Basemaps
         * @description Offline basemaps: every PMTiles archive placed in the tiles directory.
         */
        get: operations["list_basemaps_api_v1_map_basemaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/overlays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Overlays */
        get: operations["list_overlays_api_v1_map_overlays_get"];
        put?: never;
        /** Create Overlay */
        post: operations["create_overlay_api_v1_map_overlays_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/overlays/{overlay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Overlay */
        delete: operations["delete_overlay_api_v1_map_overlays__overlay_id__delete"];
        options?: never;
        head?: never;
        /** Update Overlay */
        patch: operations["update_overlay_api_v1_map_overlays__overlay_id__patch"];
        trace?: never;
    };
    "/api/v1/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Changes */
        get: operations["list_changes_api_v1_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/catalogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogue */
        get: operations["catalogue_api_v1_kpi_catalogue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Report
         * @description Load an hourly per-cell KPI report; repeated hours replace the stored values.
         */
        post: operations["import_report_api_v1_kpi_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["list_files_api_v1_kpi_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description Every cell's KPI over the period: the value (see the catalogue) and the worst hour.
         */
        get: operations["summary_api_v1_kpi_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cells/{cell_id}/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cell Series
         * @description Hourly KPI values of an inventory cell.
         */
        get: operations["cell_series_api_v1_cells__cell_id__kpi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reconciliation
         * @description Differences between the operator's statistics and the inventory.
         */
        get: operations["reconciliation_api_v1_kpi_reconciliation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/operator-cells/{kpi_cell_id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Link
         * @description Link a statistics cell to an inventory cell (optionally renaming the inventory cell).
         */
        put: operations["link_api_v1_kpi_operator_cells__kpi_cell_id__link_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Aggregate
         * @enum {string}
         */
        Aggregate: "mean" | "traffic" | "sum";
        /** AssetCreate */
        AssetCreate: {
            /** @default other */
            kind: components["schemas"]["AssetKind"];
            /** Model */
            model?: string | null;
            /** Notes */
            notes?: string | null;
            /** Name */
            name: string;
        };
        /**
         * AssetKind
         * @enum {string}
         */
        AssetKind: "haul_truck" | "excavator" | "drill" | "dozer" | "loader" | "light_vehicle" | "other";
        /** AssetRead */
        AssetRead: {
            /** @default other */
            kind: components["schemas"]["AssetKind"];
            /** Model */
            model?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AssetUpdate */
        AssetUpdate: {
            /** Name */
            name?: string | null;
            kind?: components["schemas"]["AssetKind"] | null;
            /** Model */
            model?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** Basemap */
        Basemap: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "raster" | "vector";
            /** Tile Type */
            tile_type: string;
            /** Schema Name */
            schema_name: ("protomaps" | "generic") | null;
            /** Vector Layers */
            vector_layers: string[];
            /** Min Zoom */
            min_zoom: number;
            /** Max Zoom */
            max_zoom: number;
            /** Bounds */
            bounds: [
                number,
                number,
                number,
                number
            ];
            /** Center */
            center: [
                number,
                number,
                number
            ];
            /** Attribution */
            attribution: string | null;
        };
        /**
         * Better
         * @enum {string}
         */
        Better: "high" | "low";
        /** Body_import_file_api_v1_inventory_import_post */
        Body_import_file_api_v1_inventory_import_post: {
            /** File */
            file: string;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            /** Effective At */
            effective_at?: string | null;
        };
        /** Body_import_report_api_v1_kpi_import_post */
        Body_import_report_api_v1_kpi_import_post: {
            /** File */
            file: string;
            /**
             * Timezone
             * @description Часовой пояс времени в отчёте
             * @default Asia/Almaty
             */
            timezone: string;
        };
        /** CellCreate */
        CellCreate: {
            /** Name */
            name?: string | null;
            /** @default active */
            status: components["schemas"]["Status"];
            /** Pci */
            pci: number;
            /** Earfcn Dl */
            earfcn_dl: number;
            /** Earfcn Ul */
            earfcn_ul?: number | null;
            /** Bandwidth Mhz */
            bandwidth_mhz?: number | null;
            /** Tac */
            tac?: number | null;
            /** Max Tx Power Dbm */
            max_tx_power_dbm?: number | null;
            /** Antenna Model */
            antenna_model?: string | null;
            /** Height M */
            height_m?: number | null;
            /** Azimuth Deg */
            azimuth_deg?: number | null;
            /** Mech Tilt Deg */
            mech_tilt_deg?: number | null;
            /** Elec Tilt Deg */
            elec_tilt_deg?: number | null;
            /** Beamwidth Deg */
            beamwidth_deg?: number | null;
            /** Notes */
            notes?: string | null;
            /** Enodeb Id */
            enodeb_id: number;
            /** Site Id */
            site_id?: number | null;
            /** Local Cell Id */
            local_cell_id: number;
        };
        /** CellRead */
        CellRead: {
            /** Name */
            name?: string | null;
            /** @default active */
            status: components["schemas"]["Status"];
            /** Pci */
            pci: number;
            /** Earfcn Dl */
            earfcn_dl: number;
            /** Earfcn Ul */
            earfcn_ul?: number | null;
            /** Bandwidth Mhz */
            bandwidth_mhz?: number | null;
            /** Tac */
            tac?: number | null;
            /** Max Tx Power Dbm */
            max_tx_power_dbm?: number | null;
            /** Antenna Model */
            antenna_model?: string | null;
            /** Height M */
            height_m?: number | null;
            /** Azimuth Deg */
            azimuth_deg?: number | null;
            /** Mech Tilt Deg */
            mech_tilt_deg?: number | null;
            /** Elec Tilt Deg */
            elec_tilt_deg?: number | null;
            /** Beamwidth Deg */
            beamwidth_deg?: number | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Enodeb Id */
            enodeb_id: number;
            /** Enb Id */
            enb_id: number;
            /** Site Id */
            site_id: number;
            /** Site Code */
            site_code: string;
            /** Enodeb Site Id */
            enodeb_site_id: number;
            /** Enodeb Site Code */
            enodeb_site_code: string;
            /** Local Cell Id */
            local_cell_id: number;
            /** Eci */
            eci: number;
            /** Band */
            band: number | null;
            /** Dl Frequency Mhz */
            dl_frequency_mhz: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CellUpdate */
        CellUpdate: {
            /** Effective At */
            effective_at?: string | null;
            /** Enodeb Id */
            enodeb_id?: number | null;
            /** Site Id */
            site_id?: number | null;
            /** Local Cell Id */
            local_cell_id?: number | null;
            /** Name */
            name?: string | null;
            status?: components["schemas"]["Status"] | null;
            /** Pci */
            pci?: number | null;
            /** Earfcn Dl */
            earfcn_dl?: number | null;
            /** Earfcn Ul */
            earfcn_ul?: number | null;
            /** Bandwidth Mhz */
            bandwidth_mhz?: number | null;
            /** Tac */
            tac?: number | null;
            /** Max Tx Power Dbm */
            max_tx_power_dbm?: number | null;
            /** Antenna Model */
            antenna_model?: string | null;
            /** Height M */
            height_m?: number | null;
            /** Azimuth Deg */
            azimuth_deg?: number | null;
            /** Mech Tilt Deg */
            mech_tilt_deg?: number | null;
            /** Elec Tilt Deg */
            elec_tilt_deg?: number | null;
            /** Beamwidth Deg */
            beamwidth_deg?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** CellVersionRead */
        CellVersionRead: {
            /** Valid From */
            valid_from: string | null;
            /** Valid To */
            valid_to: string | null;
            /** Site Id */
            site_id: number;
            /** Enb Id */
            enb_id: number;
            /** Local Cell Id */
            local_cell_id: number;
            /** Eci */
            eci: number;
            status: components["schemas"]["Status"];
            /** Pci */
            pci: number;
            /** Earfcn Dl */
            earfcn_dl: number;
            /** Earfcn Ul */
            earfcn_ul: number | null;
            /** Band */
            band: number | null;
            /** Bandwidth Mhz */
            bandwidth_mhz: number | null;
            /** Tac */
            tac: number | null;
            /** Max Tx Power Dbm */
            max_tx_power_dbm: number | null;
            /** Antenna Model */
            antenna_model: string | null;
            /** Height M */
            height_m: number | null;
            /** Azimuth Deg */
            azimuth_deg: number | null;
            /** Mech Tilt Deg */
            mech_tilt_deg: number | null;
            /** Elec Tilt Deg */
            elec_tilt_deg: number | null;
            /** Beamwidth Deg */
            beamwidth_deg: number | null;
        };
        /**
         * ChangeAction
         * @enum {string}
         */
        ChangeAction: "create" | "update" | "delete";
        /** ChangeRead */
        ChangeRead: {
            /** Id */
            id: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Username */
            username: string | null;
            source: components["schemas"]["ChangeSource"];
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: number;
            /** Entity Label */
            entity_label: string | null;
            action: components["schemas"]["ChangeAction"];
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
            /** Comment */
            comment: string | null;
        };
        /**
         * ChangeSource
         * @enum {string}
         */
        ChangeSource: "ui" | "import" | "api" | "system";
        /** DeviceCreate */
        DeviceCreate: {
            kind: components["schemas"]["DeviceKind"];
            /** @default active */
            status: components["schemas"]["Status"];
            /** Imei */
            imei?: string | null;
            /** Imsi */
            imsi?: string | null;
            /** Iccid */
            iccid?: string | null;
            /** Model */
            model?: string | null;
            /** Asset Id */
            asset_id?: number | null;
            /** Role */
            role?: string | null;
            /** Notes */
            notes?: string | null;
            /** Name */
            name: string;
        };
        /**
         * DeviceKind
         * @enum {string}
         */
        DeviceKind: "phone" | "router" | "radio" | "probe" | "other";
        /** DeviceRead */
        DeviceRead: {
            kind: components["schemas"]["DeviceKind"];
            /** @default active */
            status: components["schemas"]["Status"];
            /** Imei */
            imei?: string | null;
            /** Imsi */
            imsi?: string | null;
            /** Iccid */
            iccid?: string | null;
            /** Model */
            model?: string | null;
            /** Asset Id */
            asset_id?: number | null;
            /** Role */
            role?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DeviceUpdate */
        DeviceUpdate: {
            /** Name */
            name?: string | null;
            kind?: components["schemas"]["DeviceKind"] | null;
            status?: components["schemas"]["Status"] | null;
            /** Imei */
            imei?: string | null;
            /** Imsi */
            imsi?: string | null;
            /** Iccid */
            iccid?: string | null;
            /** Model */
            model?: string | null;
            /** Asset Id */
            asset_id?: number | null;
            /** Role */
            role?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ENodeBCreate */
        ENodeBCreate: {
            /** Name */
            name?: string | null;
            /** Vendor */
            vendor?: string | null;
            /** Hw Model */
            hw_model?: string | null;
            /** Sw Version */
            sw_version?: string | null;
            /** @default active */
            status: components["schemas"]["Status"];
            /** Notes */
            notes?: string | null;
            /** Site Id */
            site_id: number;
            /** Enb Id */
            enb_id: number;
        };
        /** ENodeBRead */
        ENodeBRead: {
            /** Name */
            name?: string | null;
            /** Vendor */
            vendor?: string | null;
            /** Hw Model */
            hw_model?: string | null;
            /** Sw Version */
            sw_version?: string | null;
            /** @default active */
            status: components["schemas"]["Status"];
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Site Id */
            site_id: number;
            /** Enb Id */
            enb_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ENodeBUpdate */
        ENodeBUpdate: {
            /** Effective At */
            effective_at?: string | null;
            /** Site Id */
            site_id?: number | null;
            /** Enb Id */
            enb_id?: number | null;
            /** Name */
            name?: string | null;
            /** Vendor */
            vendor?: string | null;
            /** Hw Model */
            hw_model?: string | null;
            /** Sw Version */
            sw_version?: string | null;
            status?: components["schemas"]["Status"] | null;
            /** Notes */
            notes?: string | null;
        };
        /** EnbNameDiffRead */
        EnbNameDiffRead: {
            /** Enodeb Id */
            enodeb_id: number;
            /** Enb Id */
            enb_id: number;
            /** Name */
            name: string | null;
            /** Kpi Name */
            kpi_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportReport */
        ImportReport: {
            /** Dry Run */
            dry_run: boolean;
            /** Applied */
            applied: boolean;
            /** Sheets */
            sheets: components["schemas"]["SheetReport"][];
            /** Total Errors */
            total_errors: number;
        };
        /** InventoryCellRef */
        InventoryCellRef: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Enb Id */
            enb_id: number;
            /** Enodeb Name */
            enodeb_name: string | null;
            /** Site Code */
            site_code: string;
        };
        /** KpiCellRead */
        KpiCellRead: {
            /** Id */
            id: number;
            /** Cell Name */
            cell_name: string;
            /** Enb Name */
            enb_name: string | null;
            /** Cell Id */
            cell_id: number | null;
        };
        /** KpiCellStatsRead */
        KpiCellStatsRead: {
            /** Kpi Cell Id */
            kpi_cell_id: number;
            /** Cell Name */
            cell_name: string;
            /** Enb Name */
            enb_name: string | null;
            /** Cell Id */
            cell_id: number | null;
            /** Values */
            values: {
                [key: string]: components["schemas"]["KpiStatRead"];
            };
        };
        /** KpiDefRead */
        KpiDefRead: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Unit */
            unit: string;
            aggregate: components["schemas"]["Aggregate"];
            better: components["schemas"]["Better"] | null;
            /** Warn */
            warn: number | null;
            /** Bad */
            bad: number | null;
        };
        /** KpiFileRead */
        KpiFileRead: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Timezone */
            timezone: string;
            /** Uploaded By */
            uploaded_by: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /**
             * Period End
             * Format: date-time
             */
            period_end: string;
            /** Cells */
            cells: number;
            /** Samples */
            samples: number;
        };
        /** KpiImportRead */
        KpiImportRead: {
            file: components["schemas"]["KpiFileRead"];
            /** Sheet */
            sheet: string;
            /** Kpis */
            kpis: string[];
            /** Unknown Columns */
            unknown_columns: string[];
            /** New Cells */
            new_cells: string[];
            /** Unlinked Cells */
            unlinked_cells: string[];
        };
        /** KpiLink */
        KpiLink: {
            /** Cell Id */
            cell_id: number | null;
            /**
             * Rename
             * @default true
             */
            rename: boolean;
        };
        /** KpiPointRead */
        KpiPointRead: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Values */
            values: {
                [key: string]: number;
            };
        };
        /** KpiSeriesRead */
        KpiSeriesRead: {
            /** Cell Id */
            cell_id: number;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Points */
            points: components["schemas"]["KpiPointRead"][];
        };
        /** KpiStatRead */
        KpiStatRead: {
            /** Value */
            value: number | null;
            level: components["schemas"]["Level"] | null;
            /** Worst */
            worst: number | null;
            worst_level: components["schemas"]["Level"] | null;
            /** Hours */
            hours: number;
        };
        /** KpiSummaryRead */
        KpiSummaryRead: {
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Data Start */
            data_start: string | null;
            /** Data End */
            data_end: string | null;
            /** Cells */
            cells: components["schemas"]["KpiCellStatsRead"][];
        };
        /**
         * Level
         * @enum {string}
         */
        Level: "ok" | "warn" | "bad";
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            user: components["schemas"]["UserRead"];
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** MapCell */
        MapCell: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Eci */
            eci: number;
            /** Enb Id */
            enb_id: number;
            /** Local Cell Id */
            local_cell_id: number;
            /** Pci */
            pci: number;
            /** Earfcn Dl */
            earfcn_dl: number;
            /** Band */
            band: number | null;
            /** Bandwidth Mhz */
            bandwidth_mhz: number | null;
            /** Azimuth Deg */
            azimuth_deg: number | null;
            /** Beamwidth Deg */
            beamwidth_deg: number | null;
            /** Height M */
            height_m: number | null;
            status: components["schemas"]["Status"];
        };
        /** MapOverlayCreate */
        MapOverlayCreate: {
            /** Name */
            name: string;
            /**
             * Color
             * @default #8a8a8a
             */
            color: string;
            /**
             * Visible By Default
             * @default true
             */
            visible_by_default: boolean;
            /** Geojson */
            geojson: {
                [key: string]: unknown;
            };
        };
        /** MapOverlayRead */
        MapOverlayRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Visible By Default */
            visible_by_default: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Geojson */
            geojson: {
                [key: string]: unknown;
            };
        };
        /** MapOverlaySummary */
        MapOverlaySummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Visible By Default */
            visible_by_default: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MapOverlayUpdate */
        MapOverlayUpdate: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
            /** Visible By Default */
            visible_by_default?: boolean | null;
            /** Geojson */
            geojson?: {
                [key: string]: unknown;
            } | null;
        };
        /** MapSite */
        MapSite: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            kind: components["schemas"]["SiteKind"];
            status: components["schemas"]["Status"];
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Structure Height M */
            structure_height_m: number | null;
            /** Cells */
            cells: components["schemas"]["MapCell"][];
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ReconciliationRead */
        ReconciliationRead: {
            /** Unlinked */
            unlinked: components["schemas"]["UnlinkedKpiCellRead"][];
            /** Cells Without Kpi */
            cells_without_kpi: components["schemas"]["InventoryCellRef"][];
            /** Enb Names */
            enb_names: components["schemas"]["EnbNameDiffRead"][];
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "engineer" | "viewer";
        /** RowError */
        RowError: {
            /** Row */
            row: number;
            /** Message */
            message: string;
        };
        /** SearchHit */
        SearchHit: {
            /**
             * Type
             * @enum {string}
             */
            type: "site" | "cell" | "device" | "asset";
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Sublabel */
            sublabel?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
        };
        /** SheetReport */
        SheetReport: {
            /** Sheet */
            sheet: string;
            /**
             * Present
             * @default true
             */
            present: boolean;
            /**
             * Created
             * @default 0
             */
            created: number;
            /**
             * Updated
             * @default 0
             */
            updated: number;
            /**
             * Unchanged
             * @default 0
             */
            unchanged: number;
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["RowError"][];
        };
        /** SiteCreate */
        SiteCreate: {
            /** Name */
            name?: string | null;
            /** @default stationary */
            kind: components["schemas"]["SiteKind"];
            /** @default active */
            status: components["schemas"]["Status"];
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Structure Type */
            structure_type?: string | null;
            /** Structure Height M */
            structure_height_m?: number | null;
            /** Ground Elevation M */
            ground_elevation_m?: number | null;
            /** Notes */
            notes?: string | null;
            /** Code */
            code: string;
        };
        /**
         * SiteKind
         * @enum {string}
         */
        SiteKind: "stationary" | "mobile";
        /** SitePositionRead */
        SitePositionRead: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Valid From */
            valid_from: string | null;
            /** Valid To */
            valid_to: string | null;
        };
        /** SiteRead */
        SiteRead: {
            /** Name */
            name?: string | null;
            /** @default stationary */
            kind: components["schemas"]["SiteKind"];
            /** @default active */
            status: components["schemas"]["Status"];
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Structure Type */
            structure_type?: string | null;
            /** Structure Height M */
            structure_height_m?: number | null;
            /** Ground Elevation M */
            ground_elevation_m?: number | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SiteUpdate */
        SiteUpdate: {
            /** Effective At */
            effective_at?: string | null;
            /** Code */
            code?: string | null;
            /** Name */
            name?: string | null;
            kind?: components["schemas"]["SiteKind"] | null;
            status?: components["schemas"]["Status"] | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Structure Type */
            structure_type?: string | null;
            /** Structure Height M */
            structure_height_m?: number | null;
            /** Ground Elevation M */
            ground_elevation_m?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "planned" | "active" | "inactive" | "dismantled";
        /** UnlinkedKpiCellRead */
        UnlinkedKpiCellRead: {
            /** Kpi Cell Id */
            kpi_cell_id: number;
            /** Cell Name */
            cell_name: string;
            /** Enb Name */
            enb_name: string | null;
            /** Candidates */
            candidates: components["schemas"]["InventoryCellRef"][];
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /** Full Name */
            full_name?: string | null;
            /** @default viewer */
            role: components["schemas"]["Role"];
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Full Name */
            full_name: string | null;
            role: components["schemas"]["Role"];
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at: string | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Full Name */
            full_name?: string | null;
            role?: components["schemas"]["Role"] | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    change_password_api_v1_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sites_api_v1_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"][];
                };
            };
        };
    };
    create_site_api_v1_sites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site_api_v1_sites__site_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_site_api_v1_sites__site_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_site_api_v1_sites__site_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    site_positions_api_v1_sites__site_id__positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitePositionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_enodebs_api_v1_enodebs_get: {
        parameters: {
            query?: {
                site_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ENodeBRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_enodeb_api_v1_enodebs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ENodeBCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ENodeBRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_enodeb_api_v1_enodebs__enodeb_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enodeb_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ENodeBRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_enodeb_api_v1_enodebs__enodeb_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enodeb_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_enodeb_api_v1_enodebs__enodeb_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enodeb_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ENodeBUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ENodeBRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cells_api_v1_cells_get: {
        parameters: {
            query?: {
                site_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_cell_api_v1_cells_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CellCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cell_api_v1_cells__cell_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cell_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_cell_api_v1_cells__cell_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cell_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_cell_api_v1_cells__cell_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cell_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CellUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cell_versions_api_v1_cells__cell_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cell_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellVersionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assets_api_v1_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"][];
                };
            };
        };
    };
    create_asset_api_v1_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_v1_assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_asset_api_v1_assets__asset_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"][];
                };
            };
        };
    };
    create_device_api_v1_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_device_api_v1_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_api_v1_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    template_api_v1_inventory_template_xlsx_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_api_v1_inventory_export_xlsx_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    import_file_api_v1_inventory_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_file_api_v1_inventory_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_inventory_api_v1_map_inventory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapSite"][];
                };
            };
        };
    };
    list_basemaps_api_v1_map_basemaps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Basemap"][];
                };
            };
        };
    };
    list_overlays_api_v1_map_overlays_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapOverlayRead"][];
                };
            };
        };
    };
    create_overlay_api_v1_map_overlays_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapOverlayCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapOverlaySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_overlay_api_v1_map_overlays__overlay_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                overlay_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_overlay_api_v1_map_overlays__overlay_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                overlay_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapOverlayUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapOverlaySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_changes_api_v1_changes_get: {
        parameters: {
            query?: {
                entity_type?: string | null;
                entity_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogue_api_v1_kpi_catalogue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiDefRead"][];
                };
            };
        };
    };
    import_report_api_v1_kpi_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_report_api_v1_kpi_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiImportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_v1_kpi_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiFileRead"][];
                };
            };
        };
    };
    summary_api_v1_kpi_summary_get: {
        parameters: {
            query?: {
                /** @description Начало периода; по умолчанию неделя */
                start?: string | null;
                /** @description Конец периода; по умолчанию конец данных */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiSummaryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cell_series_api_v1_cells__cell_id__kpi_get: {
        parameters: {
            query?: {
                /** @description Начало периода; по умолчанию неделя */
                start?: string | null;
                /** @description Конец периода; по умолчанию конец данных */
                end?: string | null;
                /** @description Коды KPI; по умолчанию все */
                kpi?: string[] | null;
            };
            header?: never;
            path: {
                cell_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiSeriesRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconciliation_api_v1_kpi_reconciliation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationRead"];
                };
            };
        };
    };
    link_api_v1_kpi_operator_cells__kpi_cell_id__link_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kpi_cell_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KpiLink"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiCellRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
